on:
  workflow_dispatch:
    inputs:
      device:
        type: choice
        required: true
        options:
          - 'nothing-pong'
      recovery:
        type: choice
        required: true
        options:
          - 'twrp'
          - 'orangefox'
          - 'pitchblack'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: deps
        run: |
          sudo apt -y update
          sudo apt install -y gnupg gperf build-essential libxml2-utils xsltproc repo
      - name: build
        run: |
          sudo mkdir /mnt/build
          sudo chown $USER /mnt/build
          cp -r '${{ inputs.device }}' /mnt/build
          cd '/mnt/build/${{ inputs.device }}'
          bash '${{ inputs.recovery }}.sh'
      - uses: actions/upload-artifact@v4
        with:
          name: '${{ inputs.recovery }}-${{ inputs.device }}'
          path: '${{ inputs.recovery }}-${{ inputs.device }}.img'
