on:
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: deps
        run: |
          sudo apt -y update
          sudo apt install -y linux-modules-extra-$(uname -r) gnupg gperf build-essential libxml2-utils xsltproc repo
          sudo apt clean
      - uses: easimon/maximize-build-space@master
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-codeql: 'true'
          remove-haskell: 'true'
          remove-docker-images: 'true'
      - name: zram
        run: |
          sudo modprobe zram
          dev=$(sudo zramctl --find --algorithm zstd --size 32G)
          sudo mkswap "$dev"
          sudo swapon --priority 100 "$dev"
      - uses: actions/checkout@v4
      - name: build
        run: |
          cd nothing-spacewar
          bash orangefox.sh
      - uses: actions/upload-artifact@v4
        with:
          name: orangefox-nothing-spacewar
          path: orangefox-nothing-spacewar.img
          if-no-files-found: error
      - uses: svenstaro/upload-release-action@v2
        with:
          tag: '25.10.09'
          file: orangefox-nothing-spacewar.img
